language: generic
os: linux
services:
  - docker
branches:
  only:
  - master
before_install:
  - pwd
  - curl -fsSL https://deno.land/x/install/install.sh | sh
  - ls -l $HOME/.deno
  - export DENO_INSTALL="$HOME/.deno"
  - export PATH="$DENO_INSTALL/bin:$PATH"
  - deno run https://deno.land/std/examples/welcome.ts
script:
  - deno test
